AllCops:
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
